version: "3.9"

services:
  db:
    image: postgres:16
    container_name: parking_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1324
      POSTGRES_DB: parking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: parking_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1324@db:5432/parking_db
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8010 --reload

volumes:
  postgres_data:
